name: Check, lint, and test Rust code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly
      - run: rustup component add --toolchain nightly clippy
      - run: cargo check
      - run: cargo clippy
      - run: cargo test
